# 1. APPLICATION NAME
spring.application.name=whatsapp-clone-backend

# 2. DATABASE CONFIGURATION (PostgreSQL connection parameters)
spring.datasource.url=jdbc:postgresql://localhost:5432/chatapp
spring.datasource.username=postgres
spring.datasource.password=Neet2006@
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. HIBERNATE ORM CONFIGURATION
# ddl-auto=update means: Java class entities changes automatic database tables structure mein copy ho jayengi
spring.jpa.hibernate.ddl-auto=update
# Console logs mein run ho rahi SQL queries ko represent karne ke liye
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. SERVER CONFIGURATION
server.port=8080
